xprocs = 4
yprocs = 5

echo "&grid"
echo "!******number of points in x direction "
echo "imax    = 421"
echo "!******number of points in y direction "
echo "jmax    = 381"
echo "!******number of temporal iteration  "
echo "maxit   = 10000"
echo "!******step time"
echo "dt      = 0.01d0"
echo "!******filter parameter(<0.2)"
echo "sigmaf  = 0.1d0"
echo "!******number of interation to created a file of data outt.f90"
echo "cgd     = 100"
echo "!******number of interation to use the filter"
echo "cfd     = 1"
echo "!******number of interation to save the points in time "
echo "ctd     = 10"
echo "!******frequence of the font "
echo "wf      = 1.4d0"
echo "&end"


echo "&freeadm"
echo "!*********xdomain "
echo "mmin= -6.5d0"
echo "mmax= 14.5d0"
echo "!*********ydomain"
echo "nmin= -1.9d0"
echo "nmax=  1.9d0"
echo "!*********point1"
echo "pxr1=  9.0d0"
echo "pyr1=  0.0d0"
echo "!*********point2"
echo "pxr2=  9.0d0"
echo "pyr2=  0.8d0"
echo "!*********point3"
echo "pxr3=  9.0d0"
echo "pyr3= -0.8d0"
echo "&end"

echo "&grid"
echo "!*********Number of points in the NRBC "
echo "D       = 90"
echo "!*********Buffer NRBC parameters"
echo "c1b     = 0.01d0"
echo "c2b     = 20.0d0"
echo "c3b     = 50.0d0"
echo "&end"

echo "&mpi"
echo "!*********Number of process used by MPI "
echo "num_procs_x="$xprocs
echo "num_procs_y="$yprocs
echo "\$end"
